[project]
name = "lecture-3a-f2-esp32"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.1",
    "pandas>=2.2.3",
    "serial>=0.0.97",
]
